cluster_name: dc-ray-aws

provider:
    type: aws
    region: us-east-2
    # comment below line to stop instance instead of termination
    cache_stopped_nodes: False

max_workers: 4

available_node_types:
    ray_head_default:
        resources: {"CPU": 2, "GPU": 0}
        node_config:
            InstanceType: t3.medium 
            ImageId: ami-01f75f60014697a06
            IamInstanceProfile:
                Arn: "arn:aws:iam::979726621414:instance-profile/dc_ray_head_node_profile" 
            BlockDeviceMappings:
              - DeviceName: /dev/sda1
                Ebs:
                    VolumeSize: 150
    single_gpu_instance:
        resources: {"CPU": 4, "GPU": 1}
        node_config:
            InstanceType: g4dn.xlarge
            # The below is a custom AMI id for deep learning containing deechem, torch with cuda 12.1, ray installed.
            ImageId: ami-0c59ea116e837dd34
            IamInstanceProfile:
                Arn: "arn:aws:iam::979726621414:instance-profile/DcSpotInstanceProfile20240216110059439800000002"
            InstanceMarketOptions:
                MarketType: spot
                SpotOptions:
                    MaxPrice: "0.25"
        max_workers: 0 
    two_gpu_instance:
        resources: {"CPU": 32, "GPU": 2} 
        node_config:
            InstanceType: g3.8xlarge
            # The below is a custom AMI id for deep learning containing deechem, torch with cuda 12.1, ray installed for instance with multiple nodes.
            ImageId: ami-05c1e117e4ebd2133 
            IamInstanceProfile:
                Arn: "arn:aws:iam::979726621414:instance-profile/DcSpotInstanceProfile20240216110059439800000002"
            # To query spot price: aws ec2 describe-spot-price-history --instance-types g3.8xlarge --availability-zone us-east-2a --product-description "Linux/UNIX"
            # InstanceMarketOptions:
            #     MarketType: spot
            #     SpotOptions:
            #         MaxPrice: "1"
        max_workers: 2

head_node_type: ray_head_default
