checkpoint_interval: 4
early_stopper: true
model_name: chemberta
model_parameters:
  batch_size: 32
  learning_rate: 0.0001
  log_frequency: 10
  mode: classification
  n_classes: 2
  n_tasks: 1
  task: classification
nb_epoch: 50
patience: 10
pretrain_model_dir: runs/chemberta_mlm_zinc1m
test_data_dir: data/hiv-featurized/DummyFeaturizer/ScaffoldSplitter/BalancingTransformer/test_dir
train: true
train_data_dir: data/hiv-featurized/DummyFeaturizer/ScaffoldSplitter/BalancingTransformer/train_dir
valid_data_dir: data/hiv-featurized/DummyFeaturizer/ScaffoldSplitter/BalancingTransformer/valid_dir
