checkpoint_interval: 4
early_stopper: true
model_name: chemberta
model_parameters:
  batch_size: 64
  learning_rate: 0.0001
  log_frequency: 10
  mode: regression
  n_tasks: 1
  task: regression
nb_epoch: 50
patience: 10
pretrain_model_dir: runs/chemberta_mlm_pretrain_zinc250k
test_data_dir: data/clearance-featurized/DummyFeaturizer/ScaffoldSplitter/LogTransformer_transform_y_True/test_dir
train: true
train_data_dir: data/clearance-featurized/DummyFeaturizer/ScaffoldSplitter/LogTransformer_transform_y_True/train_dir
valid_data_dir: data/clearance-featurized/DummyFeaturizer/ScaffoldSplitter/LogTransformer_transform_y_True/valid_dir
