checkpoint_interval: 4
early_stopper: true
finetune: true
model_name: infographstar
model_parameters:
  batch_size: 100
  edge_features: 11
  embedding_dim: 128
  learning_rate: 0.0001
  log_frequency: 10
  mode: classification
  num_classes: 2
  num_features: 30
  num_tasks: 1
  task: supervised
nb_epoch: 100
patience: 10
pretrain_model_components:
- unsup_encoder
pretrain_model_dir: runs/infograph_pretrain_zinc1m
pretrain_model_parameters:
  edge_fdim: 11
  node_fdim: 30
  num_gc_layers: 3
pretrain_modular_model_name: infograph
test_data_dir: data/tox21-featurized/MolGraphConvFeaturizer_use_edges_True/ScaffoldSplitter/BalancingTransformer/test_dir
train_data_dir: data/tox21-featurized/MolGraphConvFeaturizer_use_edges_True/ScaffoldSplitter/BalancingTransformer/train_dir
valid_data_dir: data/tox21-featurized/MolGraphConvFeaturizer_use_edges_True/ScaffoldSplitter/BalancingTransformer/valid_dir
