pretrain: True

model_name: 'infomax3d'
model_parameters:
  task: 'pretraining'
  mode: 'pretraining'
  hidden_dim: 64
  target_dim: 10
  aggregators: ['mean']
  readout_aggregators: ['mean']
  scalers: ['identity']
  residual: True
  learning_rate: 0.00008
  batch_size: 500
  log_frequency: 10

nb_epoch: 1000
checkpoint_interval: 4
train_data_dir: 'data/zinc5k-featurized/RDKitConformerFeaturizer'
